### PR TITLE
Improve README.md for building on Linux

### PR DESCRIPTION
**Pull request by daschuer**
I was confused by all the additional parameters in the cmake guide. 
Fortunately it woks like usual on Linux. I have added the info to the Readme.

### CODE REVIEW

**Comment by Be-ing** [comment]
This is redundant with the existing instructions but the `make` and `sudo make install` parts are specific to Linux and won't apply with MSVC.

**Comment by ibsh** [comment]
It's been a long time since I've used any of this from the command line (what I get for using Xcode at work every day for many years) but:
- isn't the `cd build` step in the Linux instructions redundant with the `-B build` arg to `cmake`?
- the logical sense of "For all OSs" versus "For Linux" is lost on me.

**Comment by daschuer** [comment]
> isn't the cd build step in the Linux instructions redundant with the -B build arg to cmake?

Yes. Hower is better to not build the tree as super user an use "sudo make install" explicit. You also do not have to bother about any parameter.

I did this PR, because I was really struggling with the original Instructions.  It took me a while to figure out that I can use the classic method, that can be used everywhere.

https://cliutils.gitlab.io/modern-cmake/chapters/intro/running.html

**Comment by Be-ing** [comment]
`cd` into the build directory is inconvenient because you cannot rerun the command if you switch your shell to another directory.

> Hower is better to not build the tree as super user an use "sudo make install" explicit.

We could separate the `--target install` line from the `--build build` line and add `sudo` for the `--target install` line.

**Pull request closed without merging**
